version: "3.8"

services:
  db:
    image: dbimage
    networks: [mynet1]
    ports:
      - "3306:3306"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  auth_service:
    image: authimage
    networks: [mynet1]
    ports:
      - "5001:5001"
    deploy:
      replicas: 3

  book_service:
    image: bookimage
    networks: [mynet1]
    ports:
      - "5002:5002"
    deploy:
      replicas: 3

  borrow_service:
    image: borrowimage
    networks: [mynet1]
    ports:
      - "5003:5003"
    deploy:
      replicas: 3

  frontend:
    image: frontendimage
    networks: [mynet1]
    ports:
      - "5000:5000"
    deploy:
      replicas: 3

networks:
  mynet1:
    driver: overlay
