---
services:
  db:
    image: govardhan7989/project:dbimage
    ports:
      - "3306:3306"
    deploy:
      replicas: 1
  auth_service:
    image: govardhan7989/project:authimage
    ports:
      - "5001:5001"
    deploy:
      replicas: 1
    depends_on:
      - db
  book_service:
    image: govardhan7989/project:bookimage
    ports:
      - "5002:5002"
    deploy:
      replicas: 1
    depends_on:
      - db
  borrow_service:
    image: govardhan7989/project:borrowimage
    ports:
      - "5003:5003"
    deploy:
      replicas: 1
    depends_on:
      - db
  app_service:
    image: govardhan7989/project:appimage
    ports:
      - "5000:5000"
    deploy:
      replicas: 1
    depends_on:
      - auth_service
      - book_service
      - borrow_service
