version: "3.8"

services:
  db:
    image: govardhan7989/python:db
    networks: [mynet1]
    ports:
      - "3306:3306"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  auth_service:
    image: govardhan7989/python:auth
    networks: [mynet1]
    ports:
      - "5001:5001"
    deploy:
      replicas: 3

  book_service:
    image: govardhan7989/python:book
    networks: [mynet1]
    ports:
      - "5002:5002"
    deploy:
      replicas: 3

  borrow_service:
    image: govardhan7989/python:borrow   # ‚Üê indentation fixed here
    networks: [mynet1]
    ports:
      - "5003:5003"
    deploy:
      replicas: 3

  frontend:
    image: govardhan7989/python:frontend
    networks: [mynet1]
    ports:
      - "5000:5000"
    deploy:
      replicas: 3

networks:
  mynet1:
    driver: overlay
